experimental_use_rmcp_client = true
notify = ["/home/dn/.config/scripts/wezterm.py", "codex"]
model = "gpt-5.5"
personality = "pragmatic"
model_reasoning_effort = "high"
show_raw_agent_reasoning = true
approvals_reviewer = "guardian_subagent"
approval_policy = "on-request"
#sandbox_mode = "workspace-write"
sandbox_mode = "danger-full-access"
plan_mode_reasoning_effort = "high"
service_tier = "fast"
[sandbox_workspace_write]
exclude_slash_tmp = true
network_access = true

[tui]
notifications = true
status_line = ["model-with-reasoning", "current-dir", "git-branch", "context-used", "context-window-size"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[features]
multi_agent = true
guardian_approval = true

[tools]
view_image = true
runtime_metrics = true

[projects."/home/dn/cheetah"]
trust_level = "trusted"

[projects."/home/dn/helpers"]
trust_level = "trusted"

[projects."/home/dn/manager"]
trust_level = "trusted"

[projects."/home/dn/dotenv"]
trust_level = "trusted"

[projects."/home/dn/agents"]
trust_level = "trusted"

[projects."/home/dn/jarvis-mw"]
trust_level = "trusted"

[projects."/home/dn/certs"]
trust_level = "trusted"

[projects."/home/dn/dhcpcd"]
trust_level = "trusted"

[projects."/home/dn/ntpsec"]
trust_level = "trusted"

[projects."/home/dn/ejbca-ce"]
trust_level = "trusted"

[projects."/home/dn/ssh_tpm"]
trust_level = "trusted"

[projects."/tmp/all-test-plans"]
trust_level = "trusted"

[projects."/home/dn/openssl-shim-demo"]
trust_level = "trusted"

[mcp_servers.dn-mcp-server]
url = "http://ai-server:8000/mcp"

[mcp_servers.dn-mcp-server.http_headers]
X-Email-User = "aminescu@drivenets.com"
X-JIRA-TOOLS = "enabled,write"
X-CONFLUENCE-TOOLS = "enabled,write"
X-GITHUB-TOOLS = "enabled,pull_requests,write,issues"

# Resolve sensitive headers from environment variables to avoid storing tokens in git.
[mcp_servers.dn-mcp-server.env_http_headers]
X-Atlassian-Token = "ATLASIAN_TOKEN"
X-GITHUB-PERSONAL-ACCESS-TOKEN = "GITHUB_PERSONAL_ACCESS_TOKEN"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
fast_default_opt_out = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[plugins."github@openai-curated"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-08-11T06:25:42Z"
source_type = "local"
source = "/home/dn/.codex/.tmp/bundled-marketplaces/openai-bundled"
